# Generated by Django 5.1.4 on 2025-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogit', '0002_blogdetails_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetailss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogDetails',
        ),
    ]
